name=Esp32CoreClassLib
version=2v6
author=bxdobs
sentence=Esp32 Core Class Library
paragraph=Provides core functionality for ESP32 devices.
category=Communication
url=10.213.69.13       
architectures=*

